# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches: 
      - 'develop'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge develop -> master
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}
